/**
 * MVPLaunch NG - Global Platform Constants
 */
module.exports = {
  ROLES: {
    CLIENT: 'CLIENT',
    DEVELOPER: 'DEVELOPER',
    ADMIN: 'ADMIN'
  },

  IDEA_STATUS: {
    SUBMITTED: 'SUBMITTED',
    IN_REVIEW: 'IN_REVIEW',
    CLARIFIED: 'CLARIFIED',
    PROPOSAL_GENERATED: 'PROPOSAL_GENERATED',
    REJECTED: 'REJECTED'
  },

  PROJECT_STATUS: {
    DRAFT: 'DRAFT',
    PROPOSED: 'PROPOSED',
    ACCEPTED: 'ACCEPTED',
    IN_DEVELOPMENT: 'IN_DEVELOPMENT',
    IN_REVIEW: 'IN_REVIEW',
    DELIVERED: 'DELIVERED',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED'
  },

  PROPOSAL_STATUS: {
    PENDING: 'PENDING',
    ACCEPTED: 'ACCEPTED',
    DECLINED: 'DECLINED',
    EXPIRED: 'EXPIRED'
  },

  ORDER_STATUS: {
    PENDING_PAYMENT: 'PENDING_PAYMENT',
    ACTIVE: 'ACTIVE',
    COMPLETED: 'COMPLETED',
    DISPUTED: 'DISPUTED',
    CANCELLED: 'CANCELLED'
  },

  PAYMENT_STATUS: {
    INITIALIZED: 'INITIALIZED',
    SUCCESSFUL: 'SUCCESSFUL',
    FAILED: 'FAILED',
    VERIFIED: 'VERIFIED'
  },

  ORDER_PAYMENT_STATUS: {
    PENDING: 'PENDING',
    PARTIAL: 'PARTIAL',
    PAID: 'PAID',
    REFUNDED: 'REFUNDED'
  },

  MILESTONE_STATUS: {
    PENDING: 'PENDING',
    IN_PROGRESS: 'IN_PROGRESS',
    SUBMITTED: 'SUBMITTED',
    APPROVED: 'APPROVED',
    PAID: 'PAID'
  },

  TASK_STATUS: {
    TODO: 'TODO',
    IN_PROGRESS: 'IN_PROGRESS',
    DONE: 'DONE'
  },

  TASK_PRIORITY: {
    LOW: 'LOW',
    MEDIUM: 'MEDIUM',
    HIGH: 'HIGH'
  },

  FILE_CATEGORY: {
    SPEC: 'SPEC',
    DESIGN: 'DESIGN',
    ASSET: 'ASSET',
    CODE_DELIVERABLE: 'CODE_DELIVERABLE',
    RECEIPT: 'RECEIPT',
    OTHER: 'OTHER'
  },

  DEPLOYMENT_ENV: {
    STAGING: 'STAGING',
    PRODUCTION: 'PRODUCTION',
    PREVIEW: 'PREVIEW'
  },

  HANDOVER_STATUS: {
    PREPARING: 'PREPARING',
    SUBMITTED: 'SUBMITTED',
    ACCEPTED: 'ACCEPTED'
  },

  MAINTENANCE_STATUS: {
    ACTIVE: 'ACTIVE',
    PAUSED: 'PAUSED',
    CANCELLED: 'CANCELLED'
  },

  DEFAULT_CURRENCY: 'NGN'
};
